### ISSUE TITLE
Incompatible with newer versions of React (~15)

### ISSUE THREAD

**Issue by septagram** [javierbyte/react-tour#4]
Tested with React 15.5.4. I'm getting the following error whenever I try to render `<ReactTour />`:

> TypeError: this is undefined
> Stack trace:
>     at Constructor (webpack:///~/react-tour/~/react/lib/ReactClass.js:842:0)
>     at _constructComponentWithoutOwner/< (webpack:///~/react-dom/lib/ReactCompositeComponent.js:306:0)
>     at measureLifeCyclePerf (webpack:///~/react-dom/lib/ReactCompositeComponent.js:75:0)
>     at _constructComponentWithoutOwner (webpack:///~/react-dom/lib/ReactCompositeComponent.js:305:0)
>     at _constructComponent (webpack:///~/react-dom/lib/ReactCompositeComponent.js:280:0)
>     at mountComponent (webpack:///~/react-dom/lib/ReactCompositeComponent.js:188:0)
>     at mountComponent (webpack:///~/react-dom/lib/ReactReconciler.js:46:0)
>     at mountChildren (webpack:///~/react-dom/lib/ReactMultiChild.js:238:0)
>     at _createInitialChildren (webpack:///~/react-dom/lib/ReactDOMComponent.js:697:0)
>     at mountComponent (webpack:///~/react-dom/lib/ReactDOMComponent.js:516:0)
>     at mountComponent (webpack:///~/react-dom/lib/ReactReconciler.js:46:0)
>     at performInitialMount (webpack:///~/react-dom/lib/ReactCompositeComponent.js:371:0)
>     at mountComponent (webpack:///~/react-dom/lib/ReactCompositeComponent.js:258:0)
>     at mountComponent (webpack:///~/react-dom/lib/ReactReconciler.js:46:0)
>     at mountChildren (webpack:///~/react-dom/lib/ReactMultiChild.js:238:0)
>     (...etc...)
>     at mountComponentIntoNode (webpack:///~/react-dom/lib/ReactMount.js:104:0)
>     at perform (webpack:///~/react-dom/lib/Transaction.js:140:0)
>     at batchedMountComponentIntoNode (webpack:///~/react-dom/lib/ReactMount.js:126:0)
>     at perform (webpack:///~/react-dom/lib/Transaction.js:140:0)
>     at batchedUpdates (webpack:///~/react-dom/lib/ReactDefaultBatchingStrategy.js:62:0)
>     at batchedUpdates (webpack:///~/react-dom/lib/ReactUpdates.js:97:0)
>     at _renderNewRootComponent (webpack:///~/react-dom/lib/ReactMount.js:320:0)
>     at _renderSubtreeIntoContainer (webpack:///~/react-dom/lib/ReactMount.js:401:0)
>     at render (webpack:///~/react-dom/lib/ReactMount.js:422:0)
>     at (unknown) (webpack:///js/main.jsx:29:1)
>     at callback (webpack:///js/util.js:42:3)
>     at apply (webpack:///~/lodash/_apply.js:15:0)
>     at wrapper (webpack:///~/lodash/_createPartial.js:38:0)
>     at run (webpack:///~/core-js/modules/es6.promise.js:87:0)
>     at notify/< (webpack:///~/core-js/modules/es6.promise.js:100:0)
>     at flush (webpack:///~/core-js/modules/_microtask.js:18:0)

I don't think it's me, I'm getting this even when I just drop a demo component into my own.

**Comment by septagram** [comment]
It also appears to depend on react in `dependencies`, not [`peerDependencies`](https://nodejs.org/en/blog/npm/peer-dependencies/).
